---
title: Centre for the Governance of AI
author: Centre for the Governance of AI
email: operations@governance.ai
description: The Centre for the Governance of AI is creating a nonprofit
baseurl: "/ubuild-jekyll"
url: governance.ai
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
